### ISSUE TITLE
addFolderToBabelTranspile. TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by pashidlos** [bahmutov/find-webpack#18]
In case there is no `include` condition for Babel rule we should skip adding folders 

```js
The function exported by the plugins file threw an error.

We invoked the function exported by `/root/cypress/npm/react/examples/webpack-file/cypress/plugins/index.js`, but it threw an error.

 TypeError: Cannot read property 'includes' of undefined
    at addFolderToBabelTranspile (/root/cypress/npm/react/node_modules/find-webpack/src/clean-for-cypress.js:75:25)
    at /root/cypress/npm/react/node_modules/find-webpack/src/clean-for-cypress.js:183:7
    at Array.forEach (<anonymous>)
    at Object.cleanForCypress (/root/cypress/npm/react/node_modules/find-webpack/src/clean-for-cypress.js:182:16)
    at module.exports (/root/cypress/npm/react/plugins/load-webpack/index.js:46:15)
    at module.exports (/root/cypress/npm/react/examples/webpack-file/cypress/plugins/index.js:4:49)
    at /root/cypress/packages/server/lib/plugins/child/run_plugins.js:89:12
    at tryCatcher (/root/cypress/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/root/cypress/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (/root/cypress/packages/server/lib/plugins/child/run_plugins.js:86:7)
    at EventEmitter.<anonymous> (/root/cypress/packages/server/lib/plugins/child/run_plugins.js:200:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (/root/cypress/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:315:20)
    at process.emit (/root/cypress/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**Comment by dmtrKovalenko** [comment]
Is it ok? I mean I worrying that this can be some edge-case state aka "buggy" when there is no rule. If it is just missing –  I am totally ok!

**Comment by pashidlos** [comment]
@dmtrKovalenko if I understand you correctly there is already a check in case there is no babel rule
but then we assume that it always has `include` prop that could not be the case
